-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity filter_dut_true_table_4_Pipeline_TRUE_TABLE_READ is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    e_addr_strm_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    e_addr_strm_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    e_addr_strm_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    e_addr_strm_empty_n : IN STD_LOGIC;
    e_addr_strm_read : OUT STD_LOGIC;
    addr_strm_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    addr_strm_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    addr_strm_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    addr_strm_empty_n : IN STD_LOGIC;
    addr_strm_read : OUT STD_LOGIC;
    b_strm_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    b_strm_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    b_strm_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    b_strm_full_n : IN STD_LOGIC;
    b_strm_write : OUT STD_LOGIC;
    e_b_strm_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    e_b_strm_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    e_b_strm_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    e_b_strm_full_n : IN STD_LOGIC;
    e_b_strm_write : OUT STD_LOGIC;
    e : IN STD_LOGIC_VECTOR (0 downto 0);
    truetable_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    truetable_ce0 : OUT STD_LOGIC;
    truetable_q0 : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of filter_dut_true_table_4_Pipeline_TRUE_TABLE_READ is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_phi_mux_e_1_phi_fu_92_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal e_1_reg_89 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal e_1_reg_89_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal e_addr_strm_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal addr_strm_blk_n : STD_LOGIC;
    signal b_strm_blk_n : STD_LOGIC;
    signal e_b_strm_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal e_2_reg_105 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal zext_ln340_fu_100_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal e_addr_strm_read_local : STD_LOGIC;
    signal addr_strm_read_local : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal b_strm_write_local : STD_LOGIC;
    signal e_b_strm_write_local : STD_LOGIC;
    signal truetable_ce0_local : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_203 : BOOLEAN;
    signal ap_condition_208 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component filter_dut_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component filter_dut_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    e_1_reg_89_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_208)) then 
                    e_1_reg_89 <= e_2_reg_105;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1))) then 
                    e_1_reg_89 <= e;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                e_1_reg_89_pp0_iter1_reg <= e_1_reg_89;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                e_2_reg_105 <= e_addr_strm_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    addr_strm_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, addr_strm_empty_n, e_1_reg_89, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (e_1_reg_89 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            addr_strm_blk_n <= addr_strm_empty_n;
        else 
            addr_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    addr_strm_read <= addr_strm_read_local;

    addr_strm_read_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, e_1_reg_89, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (e_1_reg_89 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            addr_strm_read_local <= ap_const_logic_1;
        else 
            addr_strm_read_local <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(e_addr_strm_empty_n, ap_phi_mux_e_1_phi_fu_92_p4)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_phi_mux_e_1_phi_fu_92_p4 = ap_const_lv1_0) and (e_addr_strm_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(addr_strm_empty_n, e_1_reg_89)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((e_1_reg_89 = ap_const_lv1_0) and (ap_const_logic_0 = addr_strm_empty_n));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(b_strm_full_n, e_1_reg_89_pp0_iter1_reg, e_b_strm_full_n)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (((e_b_strm_full_n = ap_const_logic_0) and (e_1_reg_89_pp0_iter1_reg = ap_const_lv1_0)) or ((e_1_reg_89_pp0_iter1_reg = ap_const_lv1_0) and (b_strm_full_n = ap_const_logic_0)));
    end process;


    ap_condition_203_assign_proc : process(ap_enable_reg_pp0_iter1, e_1_reg_89, ap_block_pp0_stage0)
    begin
                ap_condition_203 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (e_1_reg_89 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_208_assign_proc : process(ap_enable_reg_pp0_iter1, e_1_reg_89, ap_block_pp0_stage0_11001)
    begin
                ap_condition_208 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (e_1_reg_89 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_phi_mux_e_1_phi_fu_92_p4, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_phi_mux_e_1_phi_fu_92_p4 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_e_1_phi_fu_92_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, e_1_reg_89, e, e_2_reg_105, ap_loop_init, ap_condition_203)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_203)) then 
                ap_phi_mux_e_1_phi_fu_92_p4 <= e_2_reg_105;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_e_1_phi_fu_92_p4 <= e;
            else 
                ap_phi_mux_e_1_phi_fu_92_p4 <= e_1_reg_89;
            end if;
        else 
            ap_phi_mux_e_1_phi_fu_92_p4 <= e_1_reg_89;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    b_strm_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, b_strm_full_n, e_1_reg_89_pp0_iter1_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (e_1_reg_89_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            b_strm_blk_n <= b_strm_full_n;
        else 
            b_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    b_strm_din <= truetable_q0;
    b_strm_write <= b_strm_write_local;

    b_strm_write_local_assign_proc : process(ap_enable_reg_pp0_iter2, e_1_reg_89_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (e_1_reg_89_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            b_strm_write_local <= ap_const_logic_1;
        else 
            b_strm_write_local <= ap_const_logic_0;
        end if; 
    end process;


    e_addr_strm_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, e_addr_strm_empty_n, ap_phi_mux_e_1_phi_fu_92_p4, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_phi_mux_e_1_phi_fu_92_p4 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            e_addr_strm_blk_n <= e_addr_strm_empty_n;
        else 
            e_addr_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    e_addr_strm_read <= e_addr_strm_read_local;

    e_addr_strm_read_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_phi_mux_e_1_phi_fu_92_p4, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_phi_mux_e_1_phi_fu_92_p4 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            e_addr_strm_read_local <= ap_const_logic_1;
        else 
            e_addr_strm_read_local <= ap_const_logic_0;
        end if; 
    end process;


    e_b_strm_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, e_1_reg_89_pp0_iter1_reg, e_b_strm_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (e_1_reg_89_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            e_b_strm_blk_n <= e_b_strm_full_n;
        else 
            e_b_strm_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    e_b_strm_din <= ap_const_lv1_0;
    e_b_strm_write <= e_b_strm_write_local;

    e_b_strm_write_local_assign_proc : process(ap_enable_reg_pp0_iter2, e_1_reg_89_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (e_1_reg_89_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            e_b_strm_write_local <= ap_const_logic_1;
        else 
            e_b_strm_write_local <= ap_const_logic_0;
        end if; 
    end process;

    truetable_address0 <= zext_ln340_fu_100_p1(10 - 1 downto 0);
    truetable_ce0 <= truetable_ce0_local;

    truetable_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            truetable_ce0_local <= ap_const_logic_1;
        else 
            truetable_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln340_fu_100_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(addr_strm_dout),64));
end behav;
