-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity filter_dut_var_var_cmp_32_s is
port (
    ap_ready : OUT STD_LOGIC;
    cfg : IN STD_LOGIC_VECTOR (3 downto 0);
    xu : IN STD_LOGIC_VECTOR (31 downto 0);
    yu : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of filter_dut_var_var_cmp_32_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal ap_phi_mux_ret_10_phi_fu_57_p24 : STD_LOGIC_VECTOR (0 downto 0);
    signal cfg_read_read_fu_48_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ret_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_1_fu_153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_2_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_4_fu_139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_5_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_6_fu_119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_85_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_8_fu_112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_9_fu_105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln203_fu_99_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_fu_126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_phi_mux_ret_10_phi_fu_57_p24_assign_proc : process(cfg_read_read_fu_48_p2, ret_fu_160_p2, ret_1_fu_153_p2, ret_2_fu_146_p2, grp_fu_92_p2, ret_4_fu_139_p2, ret_5_fu_132_p2, ret_6_fu_119_p2, grp_fu_85_p2, ret_8_fu_112_p2, ret_9_fu_105_p2)
    begin
        if ((not((cfg_read_read_fu_48_p2 = ap_const_lv4_A)) and not((cfg_read_read_fu_48_p2 = ap_const_lv4_9)) and not((cfg_read_read_fu_48_p2 = ap_const_lv4_8)) and not((cfg_read_read_fu_48_p2 = ap_const_lv4_7)) and not((cfg_read_read_fu_48_p2 = ap_const_lv4_6)) and not((cfg_read_read_fu_48_p2 = ap_const_lv4_5)) and not((cfg_read_read_fu_48_p2 = ap_const_lv4_4)) and not((cfg_read_read_fu_48_p2 = ap_const_lv4_3)) and not((cfg_read_read_fu_48_p2 = ap_const_lv4_2)) and not((cfg_read_read_fu_48_p2 = ap_const_lv4_1)) and not((cfg_read_read_fu_48_p2 = ap_const_lv4_0)))) then 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= ap_const_lv1_0;
        elsif ((cfg_read_read_fu_48_p2 = ap_const_lv4_A)) then 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= ret_9_fu_105_p2;
        elsif ((cfg_read_read_fu_48_p2 = ap_const_lv4_9)) then 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= ret_8_fu_112_p2;
        elsif ((cfg_read_read_fu_48_p2 = ap_const_lv4_8)) then 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= grp_fu_85_p2;
        elsif ((cfg_read_read_fu_48_p2 = ap_const_lv4_7)) then 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= ret_6_fu_119_p2;
        elsif ((cfg_read_read_fu_48_p2 = ap_const_lv4_6)) then 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= ret_5_fu_132_p2;
        elsif ((cfg_read_read_fu_48_p2 = ap_const_lv4_5)) then 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= ret_4_fu_139_p2;
        elsif ((cfg_read_read_fu_48_p2 = ap_const_lv4_4)) then 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= grp_fu_92_p2;
        elsif ((cfg_read_read_fu_48_p2 = ap_const_lv4_3)) then 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= ret_2_fu_146_p2;
        elsif ((cfg_read_read_fu_48_p2 = ap_const_lv4_2)) then 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= ret_1_fu_153_p2;
        elsif ((cfg_read_read_fu_48_p2 = ap_const_lv4_1)) then 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= ret_fu_160_p2;
        elsif ((cfg_read_read_fu_48_p2 = ap_const_lv4_0)) then 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= ap_const_lv1_1;
        else 
            ap_phi_mux_ret_10_phi_fu_57_p24 <= "X";
        end if; 
    end process;

    ap_ready <= ap_const_logic_1;
    ap_return <= ap_phi_mux_ret_10_phi_fu_57_p24;
    cfg_read_read_fu_48_p2 <= cfg;
    grp_fu_85_p2 <= "1" when (unsigned(xu) < unsigned(yu)) else "0";
    grp_fu_92_p2 <= "1" when (signed(xu) < signed(yu)) else "0";
    icmp_ln195_fu_126_p2 <= "1" when (signed(yu) < signed(xu)) else "0";
    icmp_ln203_fu_99_p2 <= "1" when (unsigned(yu) < unsigned(xu)) else "0";
    ret_1_fu_153_p2 <= "0" when (xu = yu) else "1";
    ret_2_fu_146_p2 <= "1" when (signed(xu) > signed(yu)) else "0";
    ret_4_fu_139_p2 <= (grp_fu_92_p2 xor ap_const_lv1_1);
    ret_5_fu_132_p2 <= (icmp_ln195_fu_126_p2 xor ap_const_lv1_1);
    ret_6_fu_119_p2 <= "1" when (unsigned(xu) > unsigned(yu)) else "0";
    ret_8_fu_112_p2 <= (grp_fu_85_p2 xor ap_const_lv1_1);
    ret_9_fu_105_p2 <= (icmp_ln203_fu_99_p2 xor ap_const_lv1_1);
    ret_fu_160_p2 <= "1" when (xu = yu) else "0";
end behav;
