#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("i_hash_strm_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("i_hash_strm_TVALID", 1, hls_in, 0, "axis", "in_vld", 1),
	Port_Property("i_hash_strm_TREADY", 1, hls_out, 0, "axis", "in_acc", 1),
	Port_Property("i_col1_strm_TDATA", 32, hls_in, 1, "axis", "in_data", 1),
	Port_Property("i_col1_strm_TVALID", 1, hls_in, 1, "axis", "in_vld", 1),
	Port_Property("i_col1_strm_TREADY", 1, hls_out, 1, "axis", "in_acc", 1),
	Port_Property("i_col2_strm_TDATA", 32, hls_in, 2, "axis", "in_data", 1),
	Port_Property("i_col2_strm_TVALID", 1, hls_in, 2, "axis", "in_vld", 1),
	Port_Property("i_col2_strm_TREADY", 1, hls_out, 2, "axis", "in_acc", 1),
	Port_Property("i_col3_strm_TDATA", 32, hls_in, 3, "axis", "in_data", 1),
	Port_Property("i_col3_strm_TVALID", 1, hls_in, 3, "axis", "in_vld", 1),
	Port_Property("i_col3_strm_TREADY", 1, hls_out, 3, "axis", "in_acc", 1),
	Port_Property("i_payload_strm_TDATA", 128, hls_in, 4, "axis", "in_data", 1),
	Port_Property("i_payload_strm_TVALID", 1, hls_in, 4, "axis", "in_vld", 1),
	Port_Property("i_payload_strm_TREADY", 1, hls_out, 4, "axis", "in_acc", 1),
	Port_Property("i_e_strm_TDATA", 8, hls_in, 5, "axis", "in_data", 1),
	Port_Property("i_e_strm_TVALID", 1, hls_in, 5, "axis", "in_vld", 1),
	Port_Property("i_e_strm_TREADY", 1, hls_out, 5, "axis", "in_acc", 1),
	Port_Property("i_d_key1_strm_TDATA", 32, hls_in, 6, "axis", "in_data", 1),
	Port_Property("i_d_key1_strm_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("i_d_key1_strm_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("o_hash_strm_TDATA", 32, hls_out, 7, "axis", "out_data", 1),
	Port_Property("o_hash_strm_TVALID", 1, hls_out, 7, "axis", "out_vld", 1),
	Port_Property("o_hash_strm_TREADY", 1, hls_in, 7, "axis", "out_acc", 1),
	Port_Property("o_col1_strm_TDATA", 32, hls_out, 8, "axis", "out_data", 1),
	Port_Property("o_col1_strm_TVALID", 1, hls_out, 8, "axis", "out_vld", 1),
	Port_Property("o_col1_strm_TREADY", 1, hls_in, 8, "axis", "out_acc", 1),
	Port_Property("o_col2_strm_TDATA", 32, hls_out, 9, "axis", "out_data", 1),
	Port_Property("o_col2_strm_TVALID", 1, hls_out, 9, "axis", "out_vld", 1),
	Port_Property("o_col2_strm_TREADY", 1, hls_in, 9, "axis", "out_acc", 1),
	Port_Property("o_col3_strm_TDATA", 32, hls_out, 10, "axis", "out_data", 1),
	Port_Property("o_col3_strm_TVALID", 1, hls_out, 10, "axis", "out_vld", 1),
	Port_Property("o_col3_strm_TREADY", 1, hls_in, 10, "axis", "out_acc", 1),
	Port_Property("o_payload_strm_TDATA", 128, hls_out, 11, "axis", "out_data", 1),
	Port_Property("o_payload_strm_TVALID", 1, hls_out, 11, "axis", "out_vld", 1),
	Port_Property("o_payload_strm_TREADY", 1, hls_in, 11, "axis", "out_acc", 1),
	Port_Property("o_e_strm_TDATA", 8, hls_out, 12, "axis", "out_data", 1),
	Port_Property("o_e_strm_TVALID", 1, hls_out, 12, "axis", "out_vld", 1),
	Port_Property("o_e_strm_TREADY", 1, hls_in, 12, "axis", "out_acc", 1),
};
const char* HLS_Design_Meta::dut_name = "delete_top";
