// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module filter_dut_parse_filter_config_4_32_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        filter_cfg_strm_dout,
        filter_cfg_strm_empty_n,
        filter_cfg_strm_read,
        cmpvc_cfg_strms_0_din,
        cmpvc_cfg_strms_0_num_data_valid,
        cmpvc_cfg_strms_0_fifo_cap,
        cmpvc_cfg_strms_0_full_n,
        cmpvc_cfg_strms_0_write,
        cmpvc_cfg_strms_1_din,
        cmpvc_cfg_strms_1_num_data_valid,
        cmpvc_cfg_strms_1_fifo_cap,
        cmpvc_cfg_strms_1_full_n,
        cmpvc_cfg_strms_1_write,
        cmpvc_cfg_strms_2_din,
        cmpvc_cfg_strms_2_num_data_valid,
        cmpvc_cfg_strms_2_fifo_cap,
        cmpvc_cfg_strms_2_full_n,
        cmpvc_cfg_strms_2_write,
        cmpvc_cfg_strms_3_din,
        cmpvc_cfg_strms_3_num_data_valid,
        cmpvc_cfg_strms_3_fifo_cap,
        cmpvc_cfg_strms_3_full_n,
        cmpvc_cfg_strms_3_write,
        cmpvv_cfg_strms_0_din,
        cmpvv_cfg_strms_0_num_data_valid,
        cmpvv_cfg_strms_0_fifo_cap,
        cmpvv_cfg_strms_0_full_n,
        cmpvv_cfg_strms_0_write,
        cmpvv_cfg_strms_1_din,
        cmpvv_cfg_strms_1_num_data_valid,
        cmpvv_cfg_strms_1_fifo_cap,
        cmpvv_cfg_strms_1_full_n,
        cmpvv_cfg_strms_1_write,
        cmpvv_cfg_strms_2_din,
        cmpvv_cfg_strms_2_num_data_valid,
        cmpvv_cfg_strms_2_fifo_cap,
        cmpvv_cfg_strms_2_full_n,
        cmpvv_cfg_strms_2_write,
        cmpvv_cfg_strms_3_din,
        cmpvv_cfg_strms_3_num_data_valid,
        cmpvv_cfg_strms_3_fifo_cap,
        cmpvv_cfg_strms_3_full_n,
        cmpvv_cfg_strms_3_write,
        cmpvv_cfg_strms_4_din,
        cmpvv_cfg_strms_4_num_data_valid,
        cmpvv_cfg_strms_4_fifo_cap,
        cmpvv_cfg_strms_4_full_n,
        cmpvv_cfg_strms_4_write,
        cmpvv_cfg_strms_5_din,
        cmpvv_cfg_strms_5_num_data_valid,
        cmpvv_cfg_strms_5_fifo_cap,
        cmpvv_cfg_strms_5_full_n,
        cmpvv_cfg_strms_5_write,
        tt_cfg_strm_din,
        tt_cfg_strm_num_data_valid,
        tt_cfg_strm_fifo_cap,
        tt_cfg_strm_full_n,
        tt_cfg_strm_write
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] filter_cfg_strm_dout;
input   filter_cfg_strm_empty_n;
output   filter_cfg_strm_read;
output  [71:0] cmpvc_cfg_strms_0_din;
input  [2:0] cmpvc_cfg_strms_0_num_data_valid;
input  [2:0] cmpvc_cfg_strms_0_fifo_cap;
input   cmpvc_cfg_strms_0_full_n;
output   cmpvc_cfg_strms_0_write;
output  [71:0] cmpvc_cfg_strms_1_din;
input  [2:0] cmpvc_cfg_strms_1_num_data_valid;
input  [2:0] cmpvc_cfg_strms_1_fifo_cap;
input   cmpvc_cfg_strms_1_full_n;
output   cmpvc_cfg_strms_1_write;
output  [71:0] cmpvc_cfg_strms_2_din;
input  [2:0] cmpvc_cfg_strms_2_num_data_valid;
input  [2:0] cmpvc_cfg_strms_2_fifo_cap;
input   cmpvc_cfg_strms_2_full_n;
output   cmpvc_cfg_strms_2_write;
output  [71:0] cmpvc_cfg_strms_3_din;
input  [2:0] cmpvc_cfg_strms_3_num_data_valid;
input  [2:0] cmpvc_cfg_strms_3_fifo_cap;
input   cmpvc_cfg_strms_3_full_n;
output   cmpvc_cfg_strms_3_write;
output  [3:0] cmpvv_cfg_strms_0_din;
input  [2:0] cmpvv_cfg_strms_0_num_data_valid;
input  [2:0] cmpvv_cfg_strms_0_fifo_cap;
input   cmpvv_cfg_strms_0_full_n;
output   cmpvv_cfg_strms_0_write;
output  [3:0] cmpvv_cfg_strms_1_din;
input  [2:0] cmpvv_cfg_strms_1_num_data_valid;
input  [2:0] cmpvv_cfg_strms_1_fifo_cap;
input   cmpvv_cfg_strms_1_full_n;
output   cmpvv_cfg_strms_1_write;
output  [3:0] cmpvv_cfg_strms_2_din;
input  [2:0] cmpvv_cfg_strms_2_num_data_valid;
input  [2:0] cmpvv_cfg_strms_2_fifo_cap;
input   cmpvv_cfg_strms_2_full_n;
output   cmpvv_cfg_strms_2_write;
output  [3:0] cmpvv_cfg_strms_3_din;
input  [2:0] cmpvv_cfg_strms_3_num_data_valid;
input  [2:0] cmpvv_cfg_strms_3_fifo_cap;
input   cmpvv_cfg_strms_3_full_n;
output   cmpvv_cfg_strms_3_write;
output  [3:0] cmpvv_cfg_strms_4_din;
input  [2:0] cmpvv_cfg_strms_4_num_data_valid;
input  [2:0] cmpvv_cfg_strms_4_fifo_cap;
input   cmpvv_cfg_strms_4_full_n;
output   cmpvv_cfg_strms_4_write;
output  [3:0] cmpvv_cfg_strms_5_din;
input  [2:0] cmpvv_cfg_strms_5_num_data_valid;
input  [2:0] cmpvv_cfg_strms_5_fifo_cap;
input   cmpvv_cfg_strms_5_full_n;
output   cmpvv_cfg_strms_5_write;
output  [31:0] tt_cfg_strm_din;
input  [2:0] tt_cfg_strm_num_data_valid;
input  [2:0] tt_cfg_strm_fifo_cap;
input   tt_cfg_strm_full_n;
output   tt_cfg_strm_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg filter_cfg_strm_read;
reg cmpvc_cfg_strms_0_write;
reg cmpvc_cfg_strms_1_write;
reg cmpvc_cfg_strms_2_write;
reg cmpvc_cfg_strms_3_write;
reg cmpvv_cfg_strms_0_write;
reg cmpvv_cfg_strms_1_write;
reg cmpvv_cfg_strms_2_write;
reg cmpvv_cfg_strms_3_write;
reg cmpvv_cfg_strms_4_write;
reg cmpvv_cfg_strms_5_write;
reg tt_cfg_strm_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_start;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_done;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_idle;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_ready;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_filter_cfg_strm_read;
wire   [71:0] grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_2_din;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_2_write;
wire   [71:0] grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_1_din;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_1_write;
wire   [71:0] grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_0_din;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_0_write;
wire   [71:0] grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_3_din;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_3_write;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_start;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_done;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_idle;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_ready;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_filter_cfg_strm_read;
wire   [3:0] grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_4_din;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_4_write;
wire   [3:0] grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_3_din;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_3_write;
wire   [3:0] grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_2_din;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_2_write;
wire   [3:0] grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_1_din;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_1_write;
wire   [3:0] grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_0_din;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_0_write;
wire   [3:0] grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_5_din;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_5_write;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_start;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_done;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_idle;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_ready;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_filter_cfg_strm_read;
wire   [31:0] grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_tt_cfg_strm_din;
wire    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_tt_cfg_strm_write;
reg    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_start_reg;
reg    ap_block_state1_ignore_call13;
wire    ap_CS_fsm_state2;
reg    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [7:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_start_reg = 1'b0;
#0 grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_start_reg = 1'b0;
#0 grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_start_reg = 1'b0;
end

filter_dut_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1 grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_start),
    .ap_done(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_done),
    .ap_idle(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_idle),
    .ap_ready(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_ready),
    .filter_cfg_strm_dout(filter_cfg_strm_dout),
    .filter_cfg_strm_empty_n(filter_cfg_strm_empty_n),
    .filter_cfg_strm_read(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_filter_cfg_strm_read),
    .cmpvc_cfg_strms_2_din(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_2_din),
    .cmpvc_cfg_strms_2_num_data_valid(3'd0),
    .cmpvc_cfg_strms_2_fifo_cap(3'd0),
    .cmpvc_cfg_strms_2_full_n(cmpvc_cfg_strms_2_full_n),
    .cmpvc_cfg_strms_2_write(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_2_write),
    .cmpvc_cfg_strms_1_din(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_1_din),
    .cmpvc_cfg_strms_1_num_data_valid(3'd0),
    .cmpvc_cfg_strms_1_fifo_cap(3'd0),
    .cmpvc_cfg_strms_1_full_n(cmpvc_cfg_strms_1_full_n),
    .cmpvc_cfg_strms_1_write(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_1_write),
    .cmpvc_cfg_strms_0_din(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_0_din),
    .cmpvc_cfg_strms_0_num_data_valid(3'd0),
    .cmpvc_cfg_strms_0_fifo_cap(3'd0),
    .cmpvc_cfg_strms_0_full_n(cmpvc_cfg_strms_0_full_n),
    .cmpvc_cfg_strms_0_write(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_0_write),
    .cmpvc_cfg_strms_3_din(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_3_din),
    .cmpvc_cfg_strms_3_num_data_valid(3'd0),
    .cmpvc_cfg_strms_3_fifo_cap(3'd0),
    .cmpvc_cfg_strms_3_full_n(cmpvc_cfg_strms_3_full_n),
    .cmpvc_cfg_strms_3_write(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_3_write)
);

filter_dut_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4 grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_start),
    .ap_done(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_done),
    .ap_idle(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_idle),
    .ap_ready(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_ready),
    .filter_cfg_strm_dout(filter_cfg_strm_dout),
    .filter_cfg_strm_empty_n(filter_cfg_strm_empty_n),
    .filter_cfg_strm_read(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_filter_cfg_strm_read),
    .cmpvv_cfg_strms_4_din(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_4_din),
    .cmpvv_cfg_strms_4_num_data_valid(3'd0),
    .cmpvv_cfg_strms_4_fifo_cap(3'd0),
    .cmpvv_cfg_strms_4_full_n(cmpvv_cfg_strms_4_full_n),
    .cmpvv_cfg_strms_4_write(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_4_write),
    .cmpvv_cfg_strms_3_din(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_3_din),
    .cmpvv_cfg_strms_3_num_data_valid(3'd0),
    .cmpvv_cfg_strms_3_fifo_cap(3'd0),
    .cmpvv_cfg_strms_3_full_n(cmpvv_cfg_strms_3_full_n),
    .cmpvv_cfg_strms_3_write(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_3_write),
    .cmpvv_cfg_strms_2_din(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_2_din),
    .cmpvv_cfg_strms_2_num_data_valid(3'd0),
    .cmpvv_cfg_strms_2_fifo_cap(3'd0),
    .cmpvv_cfg_strms_2_full_n(cmpvv_cfg_strms_2_full_n),
    .cmpvv_cfg_strms_2_write(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_2_write),
    .cmpvv_cfg_strms_1_din(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_1_din),
    .cmpvv_cfg_strms_1_num_data_valid(3'd0),
    .cmpvv_cfg_strms_1_fifo_cap(3'd0),
    .cmpvv_cfg_strms_1_full_n(cmpvv_cfg_strms_1_full_n),
    .cmpvv_cfg_strms_1_write(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_1_write),
    .cmpvv_cfg_strms_0_din(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_0_din),
    .cmpvv_cfg_strms_0_num_data_valid(3'd0),
    .cmpvv_cfg_strms_0_fifo_cap(3'd0),
    .cmpvv_cfg_strms_0_full_n(cmpvv_cfg_strms_0_full_n),
    .cmpvv_cfg_strms_0_write(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_0_write),
    .cmpvv_cfg_strms_5_din(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_5_din),
    .cmpvv_cfg_strms_5_num_data_valid(3'd0),
    .cmpvv_cfg_strms_5_fifo_cap(3'd0),
    .cmpvv_cfg_strms_5_full_n(cmpvv_cfg_strms_5_full_n),
    .cmpvv_cfg_strms_5_write(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_5_write)
);

filter_dut_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5 grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_start),
    .ap_done(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_done),
    .ap_idle(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_idle),
    .ap_ready(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_ready),
    .filter_cfg_strm_dout(filter_cfg_strm_dout),
    .filter_cfg_strm_empty_n(filter_cfg_strm_empty_n),
    .filter_cfg_strm_read(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_filter_cfg_strm_read),
    .tt_cfg_strm_din(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_tt_cfg_strm_din),
    .tt_cfg_strm_num_data_valid(3'd0),
    .tt_cfg_strm_fifo_cap(3'd0),
    .tt_cfg_strm_full_n(tt_cfg_strm_full_n),
    .tt_cfg_strm_write(grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_tt_cfg_strm_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state8) & (grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call13) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_start_reg <= 1'b1;
        end else if ((grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_ready == 1'b1)) begin
            grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_ready == 1'b1)) begin
            grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_start_reg <= 1'b1;
        end else if ((grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_ready == 1'b1)) begin
            grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmpvc_cfg_strms_0_write = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_0_write;
    end else begin
        cmpvc_cfg_strms_0_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmpvc_cfg_strms_1_write = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_1_write;
    end else begin
        cmpvc_cfg_strms_1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmpvc_cfg_strms_2_write = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_2_write;
    end else begin
        cmpvc_cfg_strms_2_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmpvc_cfg_strms_3_write = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_3_write;
    end else begin
        cmpvc_cfg_strms_3_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        cmpvv_cfg_strms_0_write = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_0_write;
    end else begin
        cmpvv_cfg_strms_0_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        cmpvv_cfg_strms_1_write = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_1_write;
    end else begin
        cmpvv_cfg_strms_1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        cmpvv_cfg_strms_2_write = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_2_write;
    end else begin
        cmpvv_cfg_strms_2_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        cmpvv_cfg_strms_3_write = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_3_write;
    end else begin
        cmpvv_cfg_strms_3_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        cmpvv_cfg_strms_4_write = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_4_write;
    end else begin
        cmpvv_cfg_strms_4_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        cmpvv_cfg_strms_5_write = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_5_write;
    end else begin
        cmpvv_cfg_strms_5_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        filter_cfg_strm_read = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_filter_cfg_strm_read;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        filter_cfg_strm_read = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_filter_cfg_strm_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        filter_cfg_strm_read = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_filter_cfg_strm_read;
    end else begin
        filter_cfg_strm_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tt_cfg_strm_write = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_tt_cfg_strm_write;
    end else begin
        tt_cfg_strm_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call13 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign cmpvc_cfg_strms_0_din = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_0_din;

assign cmpvc_cfg_strms_1_din = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_1_din;

assign cmpvc_cfg_strms_2_din = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_2_din;

assign cmpvc_cfg_strms_3_din = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_cmpvc_cfg_strms_3_din;

assign cmpvv_cfg_strms_0_din = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_0_din;

assign cmpvv_cfg_strms_1_din = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_1_din;

assign cmpvv_cfg_strms_2_din = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_2_din;

assign cmpvv_cfg_strms_3_din = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_3_din;

assign cmpvv_cfg_strms_4_din = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_4_din;

assign cmpvv_cfg_strms_5_din = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_cmpvv_cfg_strms_5_din;

assign grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_start = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_419_1_fu_42_ap_start_reg;

assign grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_start = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_445_4_fu_56_ap_start_reg;

assign grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_start = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_ap_start_reg;

assign start_out = real_start;

assign tt_cfg_strm_din = grp_parse_filter_config_4_32_Pipeline_VITIS_LOOP_467_5_fu_74_tt_cfg_strm_din;

endmodule //filter_dut_parse_filter_config_4_32_s
