// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="delete_top_delete_top,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu50-fsvh2104-3-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.156000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=539,HLS_SYN_LUT=437,HLS_VERSION=2024_2}" *)

module delete_top (
        ap_clk,
        ap_rst_n,
        i_hash_strm_TDATA,
        i_hash_strm_TVALID,
        i_hash_strm_TREADY,
        i_col1_strm_TDATA,
        i_col1_strm_TVALID,
        i_col1_strm_TREADY,
        i_col2_strm_TDATA,
        i_col2_strm_TVALID,
        i_col2_strm_TREADY,
        i_col3_strm_TDATA,
        i_col3_strm_TVALID,
        i_col3_strm_TREADY,
        i_payload_strm_TDATA,
        i_payload_strm_TVALID,
        i_payload_strm_TREADY,
        i_e_strm_TDATA,
        i_e_strm_TVALID,
        i_e_strm_TREADY,
        i_d_key1_strm_TDATA,
        i_d_key1_strm_TVALID,
        i_d_key1_strm_TREADY,
        o_hash_strm_TDATA,
        o_hash_strm_TVALID,
        o_hash_strm_TREADY,
        o_col1_strm_TDATA,
        o_col1_strm_TVALID,
        o_col1_strm_TREADY,
        o_col2_strm_TDATA,
        o_col2_strm_TVALID,
        o_col2_strm_TREADY,
        o_col3_strm_TDATA,
        o_col3_strm_TVALID,
        o_col3_strm_TREADY,
        o_payload_strm_TDATA,
        o_payload_strm_TVALID,
        o_payload_strm_TREADY,
        o_e_strm_TDATA,
        o_e_strm_TVALID,
        o_e_strm_TREADY
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst_n;
input  [31:0] i_hash_strm_TDATA;
input   i_hash_strm_TVALID;
output   i_hash_strm_TREADY;
input  [31:0] i_col1_strm_TDATA;
input   i_col1_strm_TVALID;
output   i_col1_strm_TREADY;
input  [31:0] i_col2_strm_TDATA;
input   i_col2_strm_TVALID;
output   i_col2_strm_TREADY;
input  [31:0] i_col3_strm_TDATA;
input   i_col3_strm_TVALID;
output   i_col3_strm_TREADY;
input  [127:0] i_payload_strm_TDATA;
input   i_payload_strm_TVALID;
output   i_payload_strm_TREADY;
input  [7:0] i_e_strm_TDATA;
input   i_e_strm_TVALID;
output   i_e_strm_TREADY;
input  [31:0] i_d_key1_strm_TDATA;
input   i_d_key1_strm_TVALID;
output   i_d_key1_strm_TREADY;
output  [31:0] o_hash_strm_TDATA;
output   o_hash_strm_TVALID;
input   o_hash_strm_TREADY;
output  [31:0] o_col1_strm_TDATA;
output   o_col1_strm_TVALID;
input   o_col1_strm_TREADY;
output  [31:0] o_col2_strm_TDATA;
output   o_col2_strm_TVALID;
input   o_col2_strm_TREADY;
output  [31:0] o_col3_strm_TDATA;
output   o_col3_strm_TVALID;
input   o_col3_strm_TREADY;
output  [127:0] o_payload_strm_TDATA;
output   o_payload_strm_TVALID;
input   o_payload_strm_TREADY;
output  [7:0] o_e_strm_TDATA;
output   o_e_strm_TVALID;
input   o_e_strm_TREADY;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
reg    i_e_strm_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    o_e_strm_TDATA_blk_n;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [0:0] e_fu_101_p1;
reg   [0:0] e_reg_105;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_done;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_idle;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_ready;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TREADY;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TREADY;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TREADY;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TREADY;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TREADY;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TREADY;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_e_strm_TREADY;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_hash_strm_TREADY;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col1_strm_TREADY;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col2_strm_TREADY;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col3_strm_TREADY;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_payload_strm_TREADY;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_d_key1_strm_TREADY;
wire   [31:0] grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TDATA;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TVALID;
wire   [31:0] grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TDATA;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TVALID;
wire   [31:0] grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TDATA;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TVALID;
wire   [31:0] grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TDATA;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TVALID;
wire   [127:0] grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TDATA;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TVALID;
wire   [7:0] grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TDATA;
wire    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TVALID;
reg    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [31:0] o_hash_strm_TDATA_reg;
reg   [31:0] o_col1_strm_TDATA_reg;
reg   [31:0] o_col2_strm_TDATA_reg;
reg   [31:0] o_col3_strm_TDATA_reg;
reg   [127:0] o_payload_strm_TDATA_reg;
reg   [7:0] o_e_strm_TDATA_reg;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_o_hash_strm_U_apdone_blk;
wire    regslice_both_o_col1_strm_U_apdone_blk;
wire    regslice_both_o_col2_strm_U_apdone_blk;
wire    regslice_both_o_col3_strm_U_apdone_blk;
wire    regslice_both_o_payload_strm_U_apdone_blk;
wire    regslice_both_o_e_strm_U_apdone_blk;
reg    ap_block_state5;
wire    regslice_both_i_hash_strm_U_apdone_blk;
wire   [31:0] i_hash_strm_TDATA_int_regslice;
wire    i_hash_strm_TVALID_int_regslice;
reg    i_hash_strm_TREADY_int_regslice;
wire    regslice_both_i_hash_strm_U_ack_in;
wire    regslice_both_i_col1_strm_U_apdone_blk;
wire   [31:0] i_col1_strm_TDATA_int_regslice;
wire    i_col1_strm_TVALID_int_regslice;
reg    i_col1_strm_TREADY_int_regslice;
wire    regslice_both_i_col1_strm_U_ack_in;
wire    regslice_both_i_col2_strm_U_apdone_blk;
wire   [31:0] i_col2_strm_TDATA_int_regslice;
wire    i_col2_strm_TVALID_int_regslice;
reg    i_col2_strm_TREADY_int_regslice;
wire    regslice_both_i_col2_strm_U_ack_in;
wire    regslice_both_i_col3_strm_U_apdone_blk;
wire   [31:0] i_col3_strm_TDATA_int_regslice;
wire    i_col3_strm_TVALID_int_regslice;
reg    i_col3_strm_TREADY_int_regslice;
wire    regslice_both_i_col3_strm_U_ack_in;
wire    regslice_both_i_payload_strm_U_apdone_blk;
wire   [127:0] i_payload_strm_TDATA_int_regslice;
wire    i_payload_strm_TVALID_int_regslice;
reg    i_payload_strm_TREADY_int_regslice;
wire    regslice_both_i_payload_strm_U_ack_in;
wire    regslice_both_i_e_strm_U_apdone_blk;
wire   [7:0] i_e_strm_TDATA_int_regslice;
wire    i_e_strm_TVALID_int_regslice;
reg    i_e_strm_TREADY_int_regslice;
wire    regslice_both_i_e_strm_U_ack_in;
wire    regslice_both_i_d_key1_strm_U_apdone_blk;
wire   [31:0] i_d_key1_strm_TDATA_int_regslice;
wire    i_d_key1_strm_TVALID_int_regslice;
reg    i_d_key1_strm_TREADY_int_regslice;
wire    regslice_both_i_d_key1_strm_U_ack_in;
reg   [31:0] o_hash_strm_TDATA_int_regslice;
wire    o_hash_strm_TREADY_int_regslice;
wire    regslice_both_o_hash_strm_U_vld_out;
reg   [31:0] o_col1_strm_TDATA_int_regslice;
wire    o_col1_strm_TREADY_int_regslice;
wire    regslice_both_o_col1_strm_U_vld_out;
reg   [31:0] o_col2_strm_TDATA_int_regslice;
wire    o_col2_strm_TREADY_int_regslice;
wire    regslice_both_o_col2_strm_U_vld_out;
reg   [31:0] o_col3_strm_TDATA_int_regslice;
wire    o_col3_strm_TREADY_int_regslice;
wire    regslice_both_o_col3_strm_U_vld_out;
reg   [127:0] o_payload_strm_TDATA_int_regslice;
wire    o_payload_strm_TREADY_int_regslice;
wire    regslice_both_o_payload_strm_U_vld_out;
reg   [7:0] o_e_strm_TDATA_int_regslice;
reg    o_e_strm_TVALID_int_regslice;
wire    o_e_strm_TREADY_int_regslice;
wire    regslice_both_o_e_strm_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 5'd1;
#0 grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start_reg = 1'b0;
end

delete_top_delete_top_Pipeline_VITIS_LOOP_24_1 grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start),
    .ap_done(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_done),
    .ap_idle(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_idle),
    .ap_ready(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_ready),
    .i_e_strm_TVALID(i_e_strm_TVALID_int_regslice),
    .i_hash_strm_TVALID(i_hash_strm_TVALID_int_regslice),
    .i_col1_strm_TVALID(i_col1_strm_TVALID_int_regslice),
    .i_col2_strm_TVALID(i_col2_strm_TVALID_int_regslice),
    .i_col3_strm_TVALID(i_col3_strm_TVALID_int_regslice),
    .i_payload_strm_TVALID(i_payload_strm_TVALID_int_regslice),
    .i_d_key1_strm_TVALID(i_d_key1_strm_TVALID_int_regslice),
    .o_hash_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TREADY),
    .o_col1_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TREADY),
    .o_col2_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TREADY),
    .o_col3_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TREADY),
    .o_payload_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TREADY),
    .o_e_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TREADY),
    .empty(e_reg_105),
    .i_e_strm_TDATA(i_e_strm_TDATA_int_regslice),
    .i_e_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_e_strm_TREADY),
    .i_hash_strm_TDATA(i_hash_strm_TDATA_int_regslice),
    .i_hash_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_hash_strm_TREADY),
    .i_col1_strm_TDATA(i_col1_strm_TDATA_int_regslice),
    .i_col1_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col1_strm_TREADY),
    .i_col2_strm_TDATA(i_col2_strm_TDATA_int_regslice),
    .i_col2_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col2_strm_TREADY),
    .i_col3_strm_TDATA(i_col3_strm_TDATA_int_regslice),
    .i_col3_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col3_strm_TREADY),
    .i_payload_strm_TDATA(i_payload_strm_TDATA_int_regslice),
    .i_payload_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_payload_strm_TREADY),
    .i_d_key1_strm_TDATA(i_d_key1_strm_TDATA_int_regslice),
    .i_d_key1_strm_TREADY(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_d_key1_strm_TREADY),
    .o_hash_strm_TDATA(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TDATA),
    .o_hash_strm_TVALID(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TVALID),
    .o_col1_strm_TDATA(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TDATA),
    .o_col1_strm_TVALID(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TVALID),
    .o_col2_strm_TDATA(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TDATA),
    .o_col2_strm_TVALID(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TVALID),
    .o_col3_strm_TDATA(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TDATA),
    .o_col3_strm_TVALID(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TVALID),
    .o_payload_strm_TDATA(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TDATA),
    .o_payload_strm_TVALID(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TVALID),
    .o_e_strm_TDATA(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TDATA),
    .o_e_strm_TVALID(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TVALID)
);

delete_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_i_hash_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(i_hash_strm_TDATA),
    .vld_in(i_hash_strm_TVALID),
    .ack_in(regslice_both_i_hash_strm_U_ack_in),
    .data_out(i_hash_strm_TDATA_int_regslice),
    .vld_out(i_hash_strm_TVALID_int_regslice),
    .ack_out(i_hash_strm_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_hash_strm_U_apdone_blk)
);

delete_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_i_col1_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(i_col1_strm_TDATA),
    .vld_in(i_col1_strm_TVALID),
    .ack_in(regslice_both_i_col1_strm_U_ack_in),
    .data_out(i_col1_strm_TDATA_int_regslice),
    .vld_out(i_col1_strm_TVALID_int_regslice),
    .ack_out(i_col1_strm_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_col1_strm_U_apdone_blk)
);

delete_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_i_col2_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(i_col2_strm_TDATA),
    .vld_in(i_col2_strm_TVALID),
    .ack_in(regslice_both_i_col2_strm_U_ack_in),
    .data_out(i_col2_strm_TDATA_int_regslice),
    .vld_out(i_col2_strm_TVALID_int_regslice),
    .ack_out(i_col2_strm_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_col2_strm_U_apdone_blk)
);

delete_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_i_col3_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(i_col3_strm_TDATA),
    .vld_in(i_col3_strm_TVALID),
    .ack_in(regslice_both_i_col3_strm_U_ack_in),
    .data_out(i_col3_strm_TDATA_int_regslice),
    .vld_out(i_col3_strm_TVALID_int_regslice),
    .ack_out(i_col3_strm_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_col3_strm_U_apdone_blk)
);

delete_top_regslice_both #(
    .DataWidth( 128 ))
regslice_both_i_payload_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(i_payload_strm_TDATA),
    .vld_in(i_payload_strm_TVALID),
    .ack_in(regslice_both_i_payload_strm_U_ack_in),
    .data_out(i_payload_strm_TDATA_int_regslice),
    .vld_out(i_payload_strm_TVALID_int_regslice),
    .ack_out(i_payload_strm_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_payload_strm_U_apdone_blk)
);

delete_top_regslice_both #(
    .DataWidth( 8 ))
regslice_both_i_e_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(i_e_strm_TDATA),
    .vld_in(i_e_strm_TVALID),
    .ack_in(regslice_both_i_e_strm_U_ack_in),
    .data_out(i_e_strm_TDATA_int_regslice),
    .vld_out(i_e_strm_TVALID_int_regslice),
    .ack_out(i_e_strm_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_e_strm_U_apdone_blk)
);

delete_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_i_d_key1_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(i_d_key1_strm_TDATA),
    .vld_in(i_d_key1_strm_TVALID),
    .ack_in(regslice_both_i_d_key1_strm_U_ack_in),
    .data_out(i_d_key1_strm_TDATA_int_regslice),
    .vld_out(i_d_key1_strm_TVALID_int_regslice),
    .ack_out(i_d_key1_strm_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_d_key1_strm_U_apdone_blk)
);

delete_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_o_hash_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(o_hash_strm_TDATA_int_regslice),
    .vld_in(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TVALID),
    .ack_in(o_hash_strm_TREADY_int_regslice),
    .data_out(o_hash_strm_TDATA),
    .vld_out(regslice_both_o_hash_strm_U_vld_out),
    .ack_out(o_hash_strm_TREADY),
    .apdone_blk(regslice_both_o_hash_strm_U_apdone_blk)
);

delete_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_o_col1_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(o_col1_strm_TDATA_int_regslice),
    .vld_in(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TVALID),
    .ack_in(o_col1_strm_TREADY_int_regslice),
    .data_out(o_col1_strm_TDATA),
    .vld_out(regslice_both_o_col1_strm_U_vld_out),
    .ack_out(o_col1_strm_TREADY),
    .apdone_blk(regslice_both_o_col1_strm_U_apdone_blk)
);

delete_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_o_col2_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(o_col2_strm_TDATA_int_regslice),
    .vld_in(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TVALID),
    .ack_in(o_col2_strm_TREADY_int_regslice),
    .data_out(o_col2_strm_TDATA),
    .vld_out(regslice_both_o_col2_strm_U_vld_out),
    .ack_out(o_col2_strm_TREADY),
    .apdone_blk(regslice_both_o_col2_strm_U_apdone_blk)
);

delete_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_o_col3_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(o_col3_strm_TDATA_int_regslice),
    .vld_in(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TVALID),
    .ack_in(o_col3_strm_TREADY_int_regslice),
    .data_out(o_col3_strm_TDATA),
    .vld_out(regslice_both_o_col3_strm_U_vld_out),
    .ack_out(o_col3_strm_TREADY),
    .apdone_blk(regslice_both_o_col3_strm_U_apdone_blk)
);

delete_top_regslice_both #(
    .DataWidth( 128 ))
regslice_both_o_payload_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(o_payload_strm_TDATA_int_regslice),
    .vld_in(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TVALID),
    .ack_in(o_payload_strm_TREADY_int_regslice),
    .data_out(o_payload_strm_TDATA),
    .vld_out(regslice_both_o_payload_strm_U_vld_out),
    .ack_out(o_payload_strm_TREADY),
    .apdone_blk(regslice_both_o_payload_strm_U_apdone_blk)
);

delete_top_regslice_both #(
    .DataWidth( 8 ))
regslice_both_o_e_strm_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(o_e_strm_TDATA_int_regslice),
    .vld_in(o_e_strm_TVALID_int_regslice),
    .ack_in(o_e_strm_TREADY_int_regslice),
    .data_out(o_e_strm_TDATA),
    .vld_out(regslice_both_o_e_strm_U_vld_out),
    .ack_out(o_e_strm_TREADY),
    .apdone_blk(regslice_both_o_e_strm_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start_reg <= 1'b1;
        end else if ((grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_ready == 1'b1)) begin
            grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        e_reg_105 <= e_fu_101_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TVALID == 1'b1))) begin
        o_col1_strm_TDATA_reg <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TVALID == 1'b1))) begin
        o_col2_strm_TDATA_reg <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TVALID == 1'b1))) begin
        o_col3_strm_TDATA_reg <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TVALID == 1'b1))) begin
        o_e_strm_TDATA_reg <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TVALID == 1'b1))) begin
        o_hash_strm_TDATA_reg <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TVALID == 1'b1))) begin
        o_payload_strm_TDATA_reg <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TDATA;
    end
end

always @ (*) begin
    if ((i_e_strm_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((o_e_strm_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_col1_strm_TREADY_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col1_strm_TREADY;
    end else begin
        i_col1_strm_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_col2_strm_TREADY_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col2_strm_TREADY;
    end else begin
        i_col2_strm_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_col3_strm_TREADY_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col3_strm_TREADY;
    end else begin
        i_col3_strm_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_d_key1_strm_TREADY_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_d_key1_strm_TREADY;
    end else begin
        i_d_key1_strm_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        i_e_strm_TDATA_blk_n = i_e_strm_TVALID_int_regslice;
    end else begin
        i_e_strm_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((i_e_strm_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_e_strm_TREADY_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_e_strm_TREADY_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_e_strm_TREADY;
    end else begin
        i_e_strm_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_hash_strm_TREADY_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_hash_strm_TREADY;
    end else begin
        i_hash_strm_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_payload_strm_TREADY_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_payload_strm_TREADY;
    end else begin
        i_payload_strm_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TVALID == 1'b1))) begin
        o_col1_strm_TDATA_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TDATA;
    end else begin
        o_col1_strm_TDATA_int_regslice = o_col1_strm_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TVALID == 1'b1))) begin
        o_col2_strm_TDATA_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TDATA;
    end else begin
        o_col2_strm_TDATA_int_regslice = o_col2_strm_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TVALID == 1'b1))) begin
        o_col3_strm_TDATA_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TDATA;
    end else begin
        o_col3_strm_TDATA_int_regslice = o_col3_strm_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        o_e_strm_TDATA_blk_n = o_e_strm_TREADY_int_regslice;
    end else begin
        o_e_strm_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((o_e_strm_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        o_e_strm_TDATA_int_regslice = 8'd1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TVALID == 1'b1))) begin
        o_e_strm_TDATA_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TDATA;
    end else begin
        o_e_strm_TDATA_int_regslice = o_e_strm_TDATA_reg;
    end
end

always @ (*) begin
    if (((o_e_strm_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        o_e_strm_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        o_e_strm_TVALID_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TVALID;
    end else begin
        o_e_strm_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TVALID == 1'b1))) begin
        o_hash_strm_TDATA_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TDATA;
    end else begin
        o_hash_strm_TDATA_int_regslice = o_hash_strm_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TVALID == 1'b1))) begin
        o_payload_strm_TDATA_int_regslice = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TDATA;
    end else begin
        o_payload_strm_TDATA_int_regslice = o_payload_strm_TDATA_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((i_e_strm_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((o_e_strm_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state5 = ((o_e_strm_TREADY_int_regslice == 1'b0) | (regslice_both_o_e_strm_U_apdone_blk == 1'b1) | (regslice_both_o_payload_strm_U_apdone_blk == 1'b1) | (regslice_both_o_col3_strm_U_apdone_blk == 1'b1) | (regslice_both_o_col2_strm_U_apdone_blk == 1'b1) | (regslice_both_o_col1_strm_U_apdone_blk == 1'b1) | (regslice_both_o_hash_strm_U_apdone_blk == 1'b1));
end

assign e_fu_101_p1 = i_e_strm_TDATA_int_regslice[0:0];

assign grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start = grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start_reg;

assign grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TREADY = (o_col1_strm_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TREADY = (o_col2_strm_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TREADY = (o_col3_strm_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TREADY = (o_e_strm_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TREADY = (o_hash_strm_TREADY_int_regslice & ap_CS_fsm_state3);

assign grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TREADY = (o_payload_strm_TREADY_int_regslice & ap_CS_fsm_state3);

assign i_col1_strm_TREADY = regslice_both_i_col1_strm_U_ack_in;

assign i_col2_strm_TREADY = regslice_both_i_col2_strm_U_ack_in;

assign i_col3_strm_TREADY = regslice_both_i_col3_strm_U_ack_in;

assign i_d_key1_strm_TREADY = regslice_both_i_d_key1_strm_U_ack_in;

assign i_e_strm_TREADY = regslice_both_i_e_strm_U_ack_in;

assign i_hash_strm_TREADY = regslice_both_i_hash_strm_U_ack_in;

assign i_payload_strm_TREADY = regslice_both_i_payload_strm_U_ack_in;

assign o_col1_strm_TVALID = regslice_both_o_col1_strm_U_vld_out;

assign o_col2_strm_TVALID = regslice_both_o_col2_strm_U_vld_out;

assign o_col3_strm_TVALID = regslice_both_o_col3_strm_U_vld_out;

assign o_e_strm_TVALID = regslice_both_o_e_strm_U_vld_out;

assign o_hash_strm_TVALID = regslice_both_o_hash_strm_U_vld_out;

assign o_payload_strm_TVALID = regslice_both_o_payload_strm_U_vld_out;

endmodule //delete_top
