-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity delete_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    i_hash_strm_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    i_hash_strm_TVALID : IN STD_LOGIC;
    i_hash_strm_TREADY : OUT STD_LOGIC;
    i_col1_strm_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    i_col1_strm_TVALID : IN STD_LOGIC;
    i_col1_strm_TREADY : OUT STD_LOGIC;
    i_col2_strm_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    i_col2_strm_TVALID : IN STD_LOGIC;
    i_col2_strm_TREADY : OUT STD_LOGIC;
    i_col3_strm_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    i_col3_strm_TVALID : IN STD_LOGIC;
    i_col3_strm_TREADY : OUT STD_LOGIC;
    i_payload_strm_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    i_payload_strm_TVALID : IN STD_LOGIC;
    i_payload_strm_TREADY : OUT STD_LOGIC;
    i_e_strm_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    i_e_strm_TVALID : IN STD_LOGIC;
    i_e_strm_TREADY : OUT STD_LOGIC;
    i_d_key1_strm_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    i_d_key1_strm_TVALID : IN STD_LOGIC;
    i_d_key1_strm_TREADY : OUT STD_LOGIC;
    o_hash_strm_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    o_hash_strm_TVALID : OUT STD_LOGIC;
    o_hash_strm_TREADY : IN STD_LOGIC;
    o_col1_strm_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    o_col1_strm_TVALID : OUT STD_LOGIC;
    o_col1_strm_TREADY : IN STD_LOGIC;
    o_col2_strm_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    o_col2_strm_TVALID : OUT STD_LOGIC;
    o_col2_strm_TREADY : IN STD_LOGIC;
    o_col3_strm_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    o_col3_strm_TVALID : OUT STD_LOGIC;
    o_col3_strm_TREADY : IN STD_LOGIC;
    o_payload_strm_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    o_payload_strm_TVALID : OUT STD_LOGIC;
    o_payload_strm_TREADY : IN STD_LOGIC;
    o_e_strm_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    o_e_strm_TVALID : OUT STD_LOGIC;
    o_e_strm_TREADY : IN STD_LOGIC );
end;


architecture behav of delete_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "delete_top_delete_top,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu50-fsvh2104-3-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.156000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=539,HLS_SYN_LUT=437,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal i_e_strm_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal o_e_strm_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal e_fu_101_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_reg_105 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_done : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_idle : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_ready : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_e_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_hash_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col1_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col2_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col3_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_payload_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_d_key1_strm_TREADY : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TVALID : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TVALID : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TVALID : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TVALID : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TVALID : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TVALID : STD_LOGIC;
    signal grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal o_hash_strm_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal o_col1_strm_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal o_col2_strm_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal o_col3_strm_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal o_payload_strm_TDATA_reg : STD_LOGIC_VECTOR (127 downto 0);
    signal o_e_strm_TDATA_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal regslice_both_o_hash_strm_U_apdone_blk : STD_LOGIC;
    signal regslice_both_o_col1_strm_U_apdone_blk : STD_LOGIC;
    signal regslice_both_o_col2_strm_U_apdone_blk : STD_LOGIC;
    signal regslice_both_o_col3_strm_U_apdone_blk : STD_LOGIC;
    signal regslice_both_o_payload_strm_U_apdone_blk : STD_LOGIC;
    signal regslice_both_o_e_strm_U_apdone_blk : STD_LOGIC;
    signal ap_block_state5 : BOOLEAN;
    signal regslice_both_i_hash_strm_U_apdone_blk : STD_LOGIC;
    signal i_hash_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal i_hash_strm_TVALID_int_regslice : STD_LOGIC;
    signal i_hash_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_i_hash_strm_U_ack_in : STD_LOGIC;
    signal regslice_both_i_col1_strm_U_apdone_blk : STD_LOGIC;
    signal i_col1_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal i_col1_strm_TVALID_int_regslice : STD_LOGIC;
    signal i_col1_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_i_col1_strm_U_ack_in : STD_LOGIC;
    signal regslice_both_i_col2_strm_U_apdone_blk : STD_LOGIC;
    signal i_col2_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal i_col2_strm_TVALID_int_regslice : STD_LOGIC;
    signal i_col2_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_i_col2_strm_U_ack_in : STD_LOGIC;
    signal regslice_both_i_col3_strm_U_apdone_blk : STD_LOGIC;
    signal i_col3_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal i_col3_strm_TVALID_int_regslice : STD_LOGIC;
    signal i_col3_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_i_col3_strm_U_ack_in : STD_LOGIC;
    signal regslice_both_i_payload_strm_U_apdone_blk : STD_LOGIC;
    signal i_payload_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal i_payload_strm_TVALID_int_regslice : STD_LOGIC;
    signal i_payload_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_i_payload_strm_U_ack_in : STD_LOGIC;
    signal regslice_both_i_e_strm_U_apdone_blk : STD_LOGIC;
    signal i_e_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal i_e_strm_TVALID_int_regslice : STD_LOGIC;
    signal i_e_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_i_e_strm_U_ack_in : STD_LOGIC;
    signal regslice_both_i_d_key1_strm_U_apdone_blk : STD_LOGIC;
    signal i_d_key1_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal i_d_key1_strm_TVALID_int_regslice : STD_LOGIC;
    signal i_d_key1_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_i_d_key1_strm_U_ack_in : STD_LOGIC;
    signal o_hash_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal o_hash_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_o_hash_strm_U_vld_out : STD_LOGIC;
    signal o_col1_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal o_col1_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_o_col1_strm_U_vld_out : STD_LOGIC;
    signal o_col2_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal o_col2_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_o_col2_strm_U_vld_out : STD_LOGIC;
    signal o_col3_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal o_col3_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_o_col3_strm_U_vld_out : STD_LOGIC;
    signal o_payload_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal o_payload_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_o_payload_strm_U_vld_out : STD_LOGIC;
    signal o_e_strm_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal o_e_strm_TVALID_int_regslice : STD_LOGIC;
    signal o_e_strm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_o_e_strm_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component delete_top_delete_top_Pipeline_VITIS_LOOP_24_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        i_e_strm_TVALID : IN STD_LOGIC;
        i_hash_strm_TVALID : IN STD_LOGIC;
        i_col1_strm_TVALID : IN STD_LOGIC;
        i_col2_strm_TVALID : IN STD_LOGIC;
        i_col3_strm_TVALID : IN STD_LOGIC;
        i_payload_strm_TVALID : IN STD_LOGIC;
        i_d_key1_strm_TVALID : IN STD_LOGIC;
        o_hash_strm_TREADY : IN STD_LOGIC;
        o_col1_strm_TREADY : IN STD_LOGIC;
        o_col2_strm_TREADY : IN STD_LOGIC;
        o_col3_strm_TREADY : IN STD_LOGIC;
        o_payload_strm_TREADY : IN STD_LOGIC;
        o_e_strm_TREADY : IN STD_LOGIC;
        empty : IN STD_LOGIC_VECTOR (0 downto 0);
        i_e_strm_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        i_e_strm_TREADY : OUT STD_LOGIC;
        i_hash_strm_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        i_hash_strm_TREADY : OUT STD_LOGIC;
        i_col1_strm_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        i_col1_strm_TREADY : OUT STD_LOGIC;
        i_col2_strm_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        i_col2_strm_TREADY : OUT STD_LOGIC;
        i_col3_strm_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        i_col3_strm_TREADY : OUT STD_LOGIC;
        i_payload_strm_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        i_payload_strm_TREADY : OUT STD_LOGIC;
        i_d_key1_strm_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        i_d_key1_strm_TREADY : OUT STD_LOGIC;
        o_hash_strm_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        o_hash_strm_TVALID : OUT STD_LOGIC;
        o_col1_strm_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        o_col1_strm_TVALID : OUT STD_LOGIC;
        o_col2_strm_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        o_col2_strm_TVALID : OUT STD_LOGIC;
        o_col3_strm_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        o_col3_strm_TVALID : OUT STD_LOGIC;
        o_payload_strm_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        o_payload_strm_TVALID : OUT STD_LOGIC;
        o_e_strm_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        o_e_strm_TVALID : OUT STD_LOGIC );
    end component;


    component delete_top_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70 : component delete_top_delete_top_Pipeline_VITIS_LOOP_24_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start,
        ap_done => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_done,
        ap_idle => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_idle,
        ap_ready => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_ready,
        i_e_strm_TVALID => i_e_strm_TVALID_int_regslice,
        i_hash_strm_TVALID => i_hash_strm_TVALID_int_regslice,
        i_col1_strm_TVALID => i_col1_strm_TVALID_int_regslice,
        i_col2_strm_TVALID => i_col2_strm_TVALID_int_regslice,
        i_col3_strm_TVALID => i_col3_strm_TVALID_int_regslice,
        i_payload_strm_TVALID => i_payload_strm_TVALID_int_regslice,
        i_d_key1_strm_TVALID => i_d_key1_strm_TVALID_int_regslice,
        o_hash_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TREADY,
        o_col1_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TREADY,
        o_col2_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TREADY,
        o_col3_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TREADY,
        o_payload_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TREADY,
        o_e_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TREADY,
        empty => e_reg_105,
        i_e_strm_TDATA => i_e_strm_TDATA_int_regslice,
        i_e_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_e_strm_TREADY,
        i_hash_strm_TDATA => i_hash_strm_TDATA_int_regslice,
        i_hash_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_hash_strm_TREADY,
        i_col1_strm_TDATA => i_col1_strm_TDATA_int_regslice,
        i_col1_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col1_strm_TREADY,
        i_col2_strm_TDATA => i_col2_strm_TDATA_int_regslice,
        i_col2_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col2_strm_TREADY,
        i_col3_strm_TDATA => i_col3_strm_TDATA_int_regslice,
        i_col3_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col3_strm_TREADY,
        i_payload_strm_TDATA => i_payload_strm_TDATA_int_regslice,
        i_payload_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_payload_strm_TREADY,
        i_d_key1_strm_TDATA => i_d_key1_strm_TDATA_int_regslice,
        i_d_key1_strm_TREADY => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_d_key1_strm_TREADY,
        o_hash_strm_TDATA => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TDATA,
        o_hash_strm_TVALID => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TVALID,
        o_col1_strm_TDATA => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TDATA,
        o_col1_strm_TVALID => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TVALID,
        o_col2_strm_TDATA => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TDATA,
        o_col2_strm_TVALID => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TVALID,
        o_col3_strm_TDATA => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TDATA,
        o_col3_strm_TVALID => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TVALID,
        o_payload_strm_TDATA => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TDATA,
        o_payload_strm_TVALID => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TVALID,
        o_e_strm_TDATA => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TDATA,
        o_e_strm_TVALID => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TVALID);

    regslice_both_i_hash_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => i_hash_strm_TDATA,
        vld_in => i_hash_strm_TVALID,
        ack_in => regslice_both_i_hash_strm_U_ack_in,
        data_out => i_hash_strm_TDATA_int_regslice,
        vld_out => i_hash_strm_TVALID_int_regslice,
        ack_out => i_hash_strm_TREADY_int_regslice,
        apdone_blk => regslice_both_i_hash_strm_U_apdone_blk);

    regslice_both_i_col1_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => i_col1_strm_TDATA,
        vld_in => i_col1_strm_TVALID,
        ack_in => regslice_both_i_col1_strm_U_ack_in,
        data_out => i_col1_strm_TDATA_int_regslice,
        vld_out => i_col1_strm_TVALID_int_regslice,
        ack_out => i_col1_strm_TREADY_int_regslice,
        apdone_blk => regslice_both_i_col1_strm_U_apdone_blk);

    regslice_both_i_col2_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => i_col2_strm_TDATA,
        vld_in => i_col2_strm_TVALID,
        ack_in => regslice_both_i_col2_strm_U_ack_in,
        data_out => i_col2_strm_TDATA_int_regslice,
        vld_out => i_col2_strm_TVALID_int_regslice,
        ack_out => i_col2_strm_TREADY_int_regslice,
        apdone_blk => regslice_both_i_col2_strm_U_apdone_blk);

    regslice_both_i_col3_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => i_col3_strm_TDATA,
        vld_in => i_col3_strm_TVALID,
        ack_in => regslice_both_i_col3_strm_U_ack_in,
        data_out => i_col3_strm_TDATA_int_regslice,
        vld_out => i_col3_strm_TVALID_int_regslice,
        ack_out => i_col3_strm_TREADY_int_regslice,
        apdone_blk => regslice_both_i_col3_strm_U_apdone_blk);

    regslice_both_i_payload_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => i_payload_strm_TDATA,
        vld_in => i_payload_strm_TVALID,
        ack_in => regslice_both_i_payload_strm_U_ack_in,
        data_out => i_payload_strm_TDATA_int_regslice,
        vld_out => i_payload_strm_TVALID_int_regslice,
        ack_out => i_payload_strm_TREADY_int_regslice,
        apdone_blk => regslice_both_i_payload_strm_U_apdone_blk);

    regslice_both_i_e_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => i_e_strm_TDATA,
        vld_in => i_e_strm_TVALID,
        ack_in => regslice_both_i_e_strm_U_ack_in,
        data_out => i_e_strm_TDATA_int_regslice,
        vld_out => i_e_strm_TVALID_int_regslice,
        ack_out => i_e_strm_TREADY_int_regslice,
        apdone_blk => regslice_both_i_e_strm_U_apdone_blk);

    regslice_both_i_d_key1_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => i_d_key1_strm_TDATA,
        vld_in => i_d_key1_strm_TVALID,
        ack_in => regslice_both_i_d_key1_strm_U_ack_in,
        data_out => i_d_key1_strm_TDATA_int_regslice,
        vld_out => i_d_key1_strm_TVALID_int_regslice,
        ack_out => i_d_key1_strm_TREADY_int_regslice,
        apdone_blk => regslice_both_i_d_key1_strm_U_apdone_blk);

    regslice_both_o_hash_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => o_hash_strm_TDATA_int_regslice,
        vld_in => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TVALID,
        ack_in => o_hash_strm_TREADY_int_regslice,
        data_out => o_hash_strm_TDATA,
        vld_out => regslice_both_o_hash_strm_U_vld_out,
        ack_out => o_hash_strm_TREADY,
        apdone_blk => regslice_both_o_hash_strm_U_apdone_blk);

    regslice_both_o_col1_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => o_col1_strm_TDATA_int_regslice,
        vld_in => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TVALID,
        ack_in => o_col1_strm_TREADY_int_regslice,
        data_out => o_col1_strm_TDATA,
        vld_out => regslice_both_o_col1_strm_U_vld_out,
        ack_out => o_col1_strm_TREADY,
        apdone_blk => regslice_both_o_col1_strm_U_apdone_blk);

    regslice_both_o_col2_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => o_col2_strm_TDATA_int_regslice,
        vld_in => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TVALID,
        ack_in => o_col2_strm_TREADY_int_regslice,
        data_out => o_col2_strm_TDATA,
        vld_out => regslice_both_o_col2_strm_U_vld_out,
        ack_out => o_col2_strm_TREADY,
        apdone_blk => regslice_both_o_col2_strm_U_apdone_blk);

    regslice_both_o_col3_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => o_col3_strm_TDATA_int_regslice,
        vld_in => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TVALID,
        ack_in => o_col3_strm_TREADY_int_regslice,
        data_out => o_col3_strm_TDATA,
        vld_out => regslice_both_o_col3_strm_U_vld_out,
        ack_out => o_col3_strm_TREADY,
        apdone_blk => regslice_both_o_col3_strm_U_apdone_blk);

    regslice_both_o_payload_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => o_payload_strm_TDATA_int_regslice,
        vld_in => grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TVALID,
        ack_in => o_payload_strm_TREADY_int_regslice,
        data_out => o_payload_strm_TDATA,
        vld_out => regslice_both_o_payload_strm_U_vld_out,
        ack_out => o_payload_strm_TREADY,
        apdone_blk => regslice_both_o_payload_strm_U_apdone_blk);

    regslice_both_o_e_strm_U : component delete_top_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => o_e_strm_TDATA_int_regslice,
        vld_in => o_e_strm_TVALID_int_regslice,
        ack_in => o_e_strm_TREADY_int_regslice,
        data_out => o_e_strm_TDATA,
        vld_out => regslice_both_o_e_strm_U_vld_out,
        ack_out => o_e_strm_TREADY,
        apdone_blk => regslice_both_o_e_strm_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_ready = ap_const_logic_1)) then 
                    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                e_reg_105 <= e_fu_101_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TVALID = ap_const_logic_1))) then
                o_col1_strm_TDATA_reg <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TVALID = ap_const_logic_1))) then
                o_col2_strm_TDATA_reg <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TVALID = ap_const_logic_1))) then
                o_col3_strm_TDATA_reg <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TVALID = ap_const_logic_1))) then
                o_e_strm_TDATA_reg <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TVALID = ap_const_logic_1))) then
                o_hash_strm_TDATA_reg <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TVALID = ap_const_logic_1))) then
                o_payload_strm_TDATA_reg <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state5, grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_done, ap_CS_fsm_state3, ap_block_state5, i_e_strm_TVALID_int_regslice, o_e_strm_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((i_e_strm_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((o_e_strm_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(i_e_strm_TVALID_int_regslice)
    begin
        if ((i_e_strm_TVALID_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_done)
    begin
        if ((grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(o_e_strm_TREADY_int_regslice)
    begin
        if ((o_e_strm_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5)
    begin
        if ((ap_const_boolean_1 = ap_block_state5)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state5_assign_proc : process(regslice_both_o_hash_strm_U_apdone_blk, regslice_both_o_col1_strm_U_apdone_blk, regslice_both_o_col2_strm_U_apdone_blk, regslice_both_o_col3_strm_U_apdone_blk, regslice_both_o_payload_strm_U_apdone_blk, regslice_both_o_e_strm_U_apdone_blk, o_e_strm_TREADY_int_regslice)
    begin
                ap_block_state5 <= ((o_e_strm_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_o_e_strm_U_apdone_blk = ap_const_logic_1) or (regslice_both_o_payload_strm_U_apdone_blk = ap_const_logic_1) or (regslice_both_o_col3_strm_U_apdone_blk = ap_const_logic_1) or (regslice_both_o_col2_strm_U_apdone_blk = ap_const_logic_1) or (regslice_both_o_col1_strm_U_apdone_blk = ap_const_logic_1) or (regslice_both_o_hash_strm_U_apdone_blk = ap_const_logic_1));
    end process;

    e_fu_101_p1 <= i_e_strm_TDATA_int_regslice(1 - 1 downto 0);
    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_ap_start_reg;
    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TREADY <= (o_col1_strm_TREADY_int_regslice and ap_CS_fsm_state3);
    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TREADY <= (o_col2_strm_TREADY_int_regslice and ap_CS_fsm_state3);
    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TREADY <= (o_col3_strm_TREADY_int_regslice and ap_CS_fsm_state3);
    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TREADY <= (o_e_strm_TREADY_int_regslice and ap_CS_fsm_state3);
    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TREADY <= (o_hash_strm_TREADY_int_regslice and ap_CS_fsm_state3);
    grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TREADY <= (o_payload_strm_TREADY_int_regslice and ap_CS_fsm_state3);
    i_col1_strm_TREADY <= regslice_both_i_col1_strm_U_ack_in;

    i_col1_strm_TREADY_int_regslice_assign_proc : process(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col1_strm_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            i_col1_strm_TREADY_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col1_strm_TREADY;
        else 
            i_col1_strm_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    i_col2_strm_TREADY <= regslice_both_i_col2_strm_U_ack_in;

    i_col2_strm_TREADY_int_regslice_assign_proc : process(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col2_strm_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            i_col2_strm_TREADY_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col2_strm_TREADY;
        else 
            i_col2_strm_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    i_col3_strm_TREADY <= regslice_both_i_col3_strm_U_ack_in;

    i_col3_strm_TREADY_int_regslice_assign_proc : process(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col3_strm_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            i_col3_strm_TREADY_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_col3_strm_TREADY;
        else 
            i_col3_strm_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    i_d_key1_strm_TREADY <= regslice_both_i_d_key1_strm_U_ack_in;

    i_d_key1_strm_TREADY_int_regslice_assign_proc : process(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_d_key1_strm_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            i_d_key1_strm_TREADY_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_d_key1_strm_TREADY;
        else 
            i_d_key1_strm_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    i_e_strm_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, i_e_strm_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            i_e_strm_TDATA_blk_n <= i_e_strm_TVALID_int_regslice;
        else 
            i_e_strm_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    i_e_strm_TREADY <= regslice_both_i_e_strm_U_ack_in;

    i_e_strm_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_e_strm_TREADY, ap_CS_fsm_state3, i_e_strm_TVALID_int_regslice)
    begin
        if (((i_e_strm_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            i_e_strm_TREADY_int_regslice <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            i_e_strm_TREADY_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_e_strm_TREADY;
        else 
            i_e_strm_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    i_hash_strm_TREADY <= regslice_both_i_hash_strm_U_ack_in;

    i_hash_strm_TREADY_int_regslice_assign_proc : process(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_hash_strm_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            i_hash_strm_TREADY_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_hash_strm_TREADY;
        else 
            i_hash_strm_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    i_payload_strm_TREADY <= regslice_both_i_payload_strm_U_ack_in;

    i_payload_strm_TREADY_int_regslice_assign_proc : process(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_payload_strm_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            i_payload_strm_TREADY_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_i_payload_strm_TREADY;
        else 
            i_payload_strm_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    o_col1_strm_TDATA_int_regslice_assign_proc : process(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TDATA, grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TVALID, ap_CS_fsm_state3, o_col1_strm_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TVALID = ap_const_logic_1))) then 
            o_col1_strm_TDATA_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col1_strm_TDATA;
        else 
            o_col1_strm_TDATA_int_regslice <= o_col1_strm_TDATA_reg;
        end if; 
    end process;

    o_col1_strm_TVALID <= regslice_both_o_col1_strm_U_vld_out;

    o_col2_strm_TDATA_int_regslice_assign_proc : process(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TDATA, grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TVALID, ap_CS_fsm_state3, o_col2_strm_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TVALID = ap_const_logic_1))) then 
            o_col2_strm_TDATA_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col2_strm_TDATA;
        else 
            o_col2_strm_TDATA_int_regslice <= o_col2_strm_TDATA_reg;
        end if; 
    end process;

    o_col2_strm_TVALID <= regslice_both_o_col2_strm_U_vld_out;

    o_col3_strm_TDATA_int_regslice_assign_proc : process(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TDATA, grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TVALID, ap_CS_fsm_state3, o_col3_strm_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TVALID = ap_const_logic_1))) then 
            o_col3_strm_TDATA_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_col3_strm_TDATA;
        else 
            o_col3_strm_TDATA_int_regslice <= o_col3_strm_TDATA_reg;
        end if; 
    end process;

    o_col3_strm_TVALID <= regslice_both_o_col3_strm_U_vld_out;

    o_e_strm_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, o_e_strm_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            o_e_strm_TDATA_blk_n <= o_e_strm_TREADY_int_regslice;
        else 
            o_e_strm_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    o_e_strm_TDATA_int_regslice_assign_proc : process(ap_CS_fsm_state4, grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TDATA, grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TVALID, ap_CS_fsm_state3, o_e_strm_TDATA_reg, o_e_strm_TREADY_int_regslice)
    begin
        if (((o_e_strm_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            o_e_strm_TDATA_int_regslice <= ap_const_lv8_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TVALID = ap_const_logic_1))) then 
            o_e_strm_TDATA_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TDATA;
        else 
            o_e_strm_TDATA_int_regslice <= o_e_strm_TDATA_reg;
        end if; 
    end process;

    o_e_strm_TVALID <= regslice_both_o_e_strm_U_vld_out;

    o_e_strm_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state4, grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TVALID, ap_CS_fsm_state3, o_e_strm_TREADY_int_regslice)
    begin
        if (((o_e_strm_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            o_e_strm_TVALID_int_regslice <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            o_e_strm_TVALID_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_e_strm_TVALID;
        else 
            o_e_strm_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    o_hash_strm_TDATA_int_regslice_assign_proc : process(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TDATA, grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TVALID, ap_CS_fsm_state3, o_hash_strm_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TVALID = ap_const_logic_1))) then 
            o_hash_strm_TDATA_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_hash_strm_TDATA;
        else 
            o_hash_strm_TDATA_int_regslice <= o_hash_strm_TDATA_reg;
        end if; 
    end process;

    o_hash_strm_TVALID <= regslice_both_o_hash_strm_U_vld_out;

    o_payload_strm_TDATA_int_regslice_assign_proc : process(grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TDATA, grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TVALID, ap_CS_fsm_state3, o_payload_strm_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TVALID = ap_const_logic_1))) then 
            o_payload_strm_TDATA_int_regslice <= grp_delete_top_Pipeline_VITIS_LOOP_24_1_fu_70_o_payload_strm_TDATA;
        else 
            o_payload_strm_TDATA_int_regslice <= o_payload_strm_TDATA_reg;
        end if; 
    end process;

    o_payload_strm_TVALID <= regslice_both_o_payload_strm_U_vld_out;
end behav;
