// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module filter_dut_true_table_4_Pipeline_TRUE_TABLE_READ (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        e_addr_strm_dout,
        e_addr_strm_num_data_valid,
        e_addr_strm_fifo_cap,
        e_addr_strm_empty_n,
        e_addr_strm_read,
        addr_strm_dout,
        addr_strm_num_data_valid,
        addr_strm_fifo_cap,
        addr_strm_empty_n,
        addr_strm_read,
        b_strm_din,
        b_strm_num_data_valid,
        b_strm_fifo_cap,
        b_strm_full_n,
        b_strm_write,
        e_b_strm_din,
        e_b_strm_num_data_valid,
        e_b_strm_fifo_cap,
        e_b_strm_full_n,
        e_b_strm_write,
        e,
        truetable_address0,
        truetable_ce0,
        truetable_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] e_addr_strm_dout;
input  [3:0] e_addr_strm_num_data_valid;
input  [3:0] e_addr_strm_fifo_cap;
input   e_addr_strm_empty_n;
output   e_addr_strm_read;
input  [9:0] addr_strm_dout;
input  [3:0] addr_strm_num_data_valid;
input  [3:0] addr_strm_fifo_cap;
input   addr_strm_empty_n;
output   addr_strm_read;
output  [0:0] b_strm_din;
input  [3:0] b_strm_num_data_valid;
input  [3:0] b_strm_fifo_cap;
input   b_strm_full_n;
output   b_strm_write;
output  [0:0] e_b_strm_din;
input  [3:0] e_b_strm_num_data_valid;
input  [3:0] e_b_strm_fifo_cap;
input   e_b_strm_full_n;
output   e_b_strm_write;
input  [0:0] e;
output  [9:0] truetable_address0;
output   truetable_ce0;
input  [0:0] truetable_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] ap_phi_mux_e_1_phi_fu_92_p4;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] e_1_reg_89;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] e_1_reg_89_pp0_iter1_reg;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    e_addr_strm_blk_n;
wire    ap_block_pp0_stage0;
reg    addr_strm_blk_n;
reg    b_strm_blk_n;
reg    e_b_strm_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] e_2_reg_105;
wire    ap_loop_init;
wire   [63:0] zext_ln340_fu_100_p1;
reg    e_addr_strm_read_local;
reg    addr_strm_read_local;
reg    ap_block_pp0_stage0_01001;
reg    b_strm_write_local;
reg    e_b_strm_write_local;
reg    truetable_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_203;
reg    ap_condition_208;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

filter_dut_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_208)) begin
            e_1_reg_89 <= e_2_reg_105;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            e_1_reg_89 <= e;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        e_1_reg_89_pp0_iter1_reg <= e_1_reg_89;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_2_reg_105 <= e_addr_strm_dout;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (e_1_reg_89 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        addr_strm_blk_n = addr_strm_empty_n;
    end else begin
        addr_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (e_1_reg_89 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        addr_strm_read_local = 1'b1;
    end else begin
        addr_strm_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_phi_mux_e_1_phi_fu_92_p4 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_203)) begin
            ap_phi_mux_e_1_phi_fu_92_p4 = e_2_reg_105;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_e_1_phi_fu_92_p4 = e;
        end else begin
            ap_phi_mux_e_1_phi_fu_92_p4 = e_1_reg_89;
        end
    end else begin
        ap_phi_mux_e_1_phi_fu_92_p4 = e_1_reg_89;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (e_1_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        b_strm_blk_n = b_strm_full_n;
    end else begin
        b_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (e_1_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        b_strm_write_local = 1'b1;
    end else begin
        b_strm_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_phi_mux_e_1_phi_fu_92_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_addr_strm_blk_n = e_addr_strm_empty_n;
    end else begin
        e_addr_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_e_1_phi_fu_92_p4 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_addr_strm_read_local = 1'b1;
    end else begin
        e_addr_strm_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (e_1_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        e_b_strm_blk_n = e_b_strm_full_n;
    end else begin
        e_b_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (e_1_reg_89_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        e_b_strm_write_local = 1'b1;
    end else begin
        e_b_strm_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        truetable_ce0_local = 1'b1;
    end else begin
        truetable_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign addr_strm_read = addr_strm_read_local;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_phi_mux_e_1_phi_fu_92_p4 == 1'd0) & (e_addr_strm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((e_1_reg_89 == 1'd0) & (1'b0 == addr_strm_empty_n));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (((e_b_strm_full_n == 1'b0) & (e_1_reg_89_pp0_iter1_reg == 1'd0)) | ((e_1_reg_89_pp0_iter1_reg == 1'd0) & (b_strm_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_203 = ((1'b0 == ap_block_pp0_stage0) & (e_1_reg_89 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_208 = ((1'b0 == ap_block_pp0_stage0_11001) & (e_1_reg_89 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_strm_din = truetable_q0;

assign b_strm_write = b_strm_write_local;

assign e_addr_strm_read = e_addr_strm_read_local;

assign e_b_strm_din = 1'd0;

assign e_b_strm_write = e_b_strm_write_local;

assign truetable_address0 = zext_ln340_fu_100_p1;

assign truetable_ce0 = truetable_ce0_local;

assign zext_ln340_fu_100_p1 = addr_strm_dout;

endmodule //filter_dut_true_table_4_Pipeline_TRUE_TABLE_READ
